# Generated by Django 3.2.5 on 2022-01-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_fileentitymodel_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileentitymodel',
            options={'verbose_name': 'Версии файлов', 'verbose_name_plural': 'Версии файлов'},
        ),
        migrations.AddField(
            model_name='fileentitymodel',
            name='title',
            field=models.CharField(default='', max_length=300, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='secure',
            field=models.BooleanField(default=False, verbose_name='Поврежден  ли'),
        ),
    ]
