# Generated by Django 3.2.5 on 2022-01-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20220117_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='secure',
            field=models.BooleanField(default=True, verbose_name='Поврежден  ли'),
        ),
    ]
