# Generated by Django 3.2.5 on 2022-01-17 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_filemodel_secure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='secure',
            new_name='check',
        ),
    ]
